CREATE DATABASE SHOPGIAY_StarPard;
GO

USE SHOPGIAY_StarPard;
GO

CREATE TABLE TAIKHOAN
(
    MATK INT IDENTITY(1,1) PRIMARY KEY,
    TENDANGNHAP NVARCHAR(50) NOT NULL UNIQUE,
    MATKHAU VARCHAR(255) NOT NULL,
    VAITRO NVARCHAR(30) NOT NULL,
    TRANGTHAI NVARCHAR(30) NOT NULL
);
GO

CREATE TABLE KHACHHANG
(
    MAKH INT IDENTITY(1,1) PRIMARY KEY,
    HOTEN NVARCHAR(100) NOT NULL,
    SDT VARCHAR(15),
    EMAIL VARCHAR(100),
    DIACHI NVARCHAR(255),
    MATK INT,

    FOREIGN KEY (MATK) REFERENCES TAIKHOAN(MATK)
);
GO

CREATE TABLE NHANVIEN
(
    MANV INT IDENTITY(1,1) PRIMARY KEY,
    HOTEN NVARCHAR(100) NOT NULL,
    SDT VARCHAR(15),
    EMAIL VARCHAR(100),
    DIACHI NVARCHAR(255),
    CHUCVU NVARCHAR(50),
    MATK INT,

    FOREIGN KEY (MATK) REFERENCES TAIKHOAN(MATK)
);
GO

CREATE TABLE DANHMUC
(
    MADM INT IDENTITY(1,1) PRIMARY KEY,
    TENDM NVARCHAR(100) NOT NULL,
    MOTA NVARCHAR(255)
);
GO

CREATE TABLE THUONGHIEU
(
    MATH INT IDENTITY(1,1) PRIMARY KEY,
    TENTH NVARCHAR(100) NOT NULL,
    MOTA NVARCHAR(255)
);
GO

CREATE TABLE KHUYENMAI
(
    MAKM INT IDENTITY(1,1) PRIMARY KEY,
    TENKM NVARCHAR(100) NOT NULL,
    PHANTRAMGIAM INT NOT NULL,
    NGAYBATDAU DATE,
    NGAYKETTHUC DATE,
    TRANGTHAI NVARCHAR(50)
);
GO

CREATE TABLE SANPHAM
(
    MASP INT IDENTITY(1,1) PRIMARY KEY,
    TENSP NVARCHAR(100) NOT NULL,
    GIA DECIMAL(18,2) NOT NULL,
    MOTA NVARCHAR(500),
    HINHANH VARCHAR(255),
    SOLUONGTON INT DEFAULT 0,
    NGAYTAO DATETIME DEFAULT GETDATE(),

    MATH INT,
    MADM INT,
    MAKM INT,

    FOREIGN KEY (MATH) REFERENCES THUONGHIEU(MATH),
    FOREIGN KEY (MADM) REFERENCES DANHMUC(MADM),
    FOREIGN KEY (MAKM) REFERENCES KHUYENMAI(MAKM)
);
GO

CREATE TABLE GIOHANG
(
    MAGH INT IDENTITY(1,1) PRIMARY KEY,
    MAKH INT NOT NULL,
    MASP INT NOT NULL,
    SOLUONG INT NOT NULL DEFAULT 1,
    NGAYTAO DATETIME DEFAULT GETDATE(),

    FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
    FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP),

    CONSTRAINT UQ_GIOHANG UNIQUE (MAKH, MASP)
);
GO

CREATE TABLE DONHANG
(
    MADH INT IDENTITY(1,1) PRIMARY KEY,
    MAKH INT NOT NULL,
    MANV INT NULL,
    NGAYDAT DATETIME DEFAULT GETDATE(),
    TONGTIEN DECIMAL(18,2) NOT NULL,
    TRANGTHAI NVARCHAR(50) DEFAULT N'Chờ xác nhận',
    DIACHINHAN NVARCHAR(255),
    PHUONGTHUCTHANHTOAN NVARCHAR(50),

    FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
    FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);
GO

CREATE TABLE CHITIETDONHANG
(
    MADH INT,
    MASP INT,
    SOLUONG INT NOT NULL,
    DONGIA DECIMAL(18,2) NOT NULL,

    PRIMARY KEY (MADH, MASP),

    FOREIGN KEY (MADH) REFERENCES DONHANG(MADH),
    FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)
);
GO

CREATE TABLE TONKHO
(
    MATONKHO INT IDENTITY(1,1) PRIMARY KEY,
    MASP INT NOT NULL,
    SOLUONGNHAP INT NOT NULL,
    SOLUONGXUAT INT DEFAULT 0,
    NGAYCAPNHAT DATETIME DEFAULT GETDATE(),

    FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)
);
GO

CREATE TABLE KHACHHANG_KHUYENMAI
(
    ID INT IDENTITY(1,1) PRIMARY KEY,
    MAKH INT NOT NULL,
    MAKM INT NOT NULL,
    DASUDUNG BIT DEFAULT 0,
    NGAYNHAN DATETIME DEFAULT GETDATE(),
    FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH),
    FOREIGN KEY(MAKM) REFERENCES KHUYENMAI(MAKM)
);

CREATE TABLE DANHGIA
(
    MADG INT IDENTITY(1,1) PRIMARY KEY,
    MAKH INT NOT NULL,
    MASP INT NOT NULL,
    SOSAO INT NOT NULL,
    NOIDUNG NVARCHAR(1000),
    NGAYDG DATETIME DEFAULT GETDATE(),

    FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
    FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP),

    CONSTRAINT CK_DANHGIA_SOSAO
        CHECK (SOSAO BETWEEN 1 AND 5)
);
GO

ALTER TABLE DONHANG
ADD MAKM INT NULL;

ALTER TABLE DONHANG
ADD CONSTRAINT FK_DONHANG_KHUYENMAI
FOREIGN KEY (MAKM)
REFERENCES KHUYENMAI(MAKM);

ALTER TABLE KHACHHANG_KHUYENMAI
ADD CONSTRAINT UQ_KH_KM UNIQUE (MAKH, MAKM);

INSERT INTO Sanpham (TENSP, Gia, HinhAnh)
VALUES
(N'Giày Grand sport', 720000, 'shoes1.jpg'),
(N'Giày da nữ', 250000, 'shoes2.jpg'),
(N'Giày Convert chuck taylor', 320000, 'shoes3.webp'),
(N'Giày Format', 820000, 'shoes4.webp'),
(N'Giày Second Sunday', 460000, 'shoes5.webp');

SELECT * FROM Taikhoan;
INSERT INTO Taikhoan(Tendangnhap, Matkhau, Vaitro, Trangthai)
VALUES ('Admin','123456','Admin',N'Đã đăng kí');

INSERT INTO Taikhoan(Tendangnhap, Matkhau, Vaitro, Trangthai)
VALUES ('Nhanvien','12345',N'Nhân viên',N'Đã đăng kí');

SELECT *
FROM Donhang

DELETE FROM Taikhoan
WHERE Tendangnhap = 'Nhanvien'
AND Matkhau = '654321';

ALTER TABLE GIOHANG
ADD Size NVARCHAR(10);

ALTER TABLE CHITIETDONHANG
ADD Size NVARCHAR(10);

ALTER TABLE DANHGIA
ADD HINHANH NVARCHAR(255) NULL;

ALTER TABLE DANHGIA
ADD VIDEO NVARCHAR(255) NULL;