CREATE DATABASE SHOPGIAY_StarPard
GO
CREATE TABLE TAIKHOAN(
    MATK INT IDENTITY(1,1) PRIMARY KEY,
    TENDANGNHAP NVARCHAR(50) NOT NULL UNIQUE,
    MATKHAU VARCHAR(50) NOT NULL,
    VAITRO NVARCHAR(30) NOT NULL,
    TRANGTHAI NVARCHAR(30) NOT NULL
);
GO
CREATE TABLE KHACHHANG(
    MAKH INT IDENTITY(1,1) PRIMARY KEY,
    HOTEN NVARCHAR(100) NOT NULL,
    SDT VARCHAR(15),
    EMAIL VARCHAR(100),
    DIACHI NVARCHAR(255),
    MATK INT,
    FOREIGN KEY(MATK) REFERENCES TAIKHOAN(MATK)
);
GO
CREATE TABLE NHANVIEN(
    MANV INT IDENTITY(1,1) PRIMARY KEY,
    HOTEN NVARCHAR(100) NOT NULL,
    SDT VARCHAR(15),
    EMAIL VARCHAR(100),
    DIACHI NVARCHAR(255),
    CHUCVU NVARCHAR(50),
    MATK INT,
    FOREIGN KEY(MATK) REFERENCES TAIKHOAN(MATK)
);
GO
CREATE TABLE THUONGHIEU(
    MATH INT IDENTITY(1,1) PRIMARY KEY,
    TENTH NVARCHAR(100) NOT NULL,
    MOTA NVARCHAR(255)
);
GO
CREATE TABLE SANPHAM(
    MASP INT IDENTITY(1,1) PRIMARY KEY,
    TENSP NVARCHAR(100) NOT NULL,
    GIA DECIMAL(18,2) NOT NULL,
    MOTA NVARCHAR(500),
    HINHANH VARCHAR(255),
    SOLUONGTON INT DEFAULT 0,
    MATH INT,
    FOREIGN KEY(MATH) REFERENCES THUONGHIEU(MATH)
);
GO
CREATE TABLE GIOHANG(
    MAGH INT IDENTITY(1,1) PRIMARY KEY,
    MAKH INT,
    NGAYTAO DATETIME DEFAULT GETDATE(),
    FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH)
);
GO
CREATE TABLE CHITIETGIOHANG(
    MAGH INT,
    MASP INT,
    SOLUONG INT NOT NULL,
    PRIMARY KEY(MAGH,MASP),
    FOREIGN KEY(MAGH) REFERENCES GIOHANG(MAGH),
    FOREIGN KEY(MASP) REFERENCES SANPHAM(MASP)
);
GO
CREATE TABLE DONHANG(
    MADH INT IDENTITY(1,1) PRIMARY KEY,
    MAKH INT,
    NGAYDAT DATETIME DEFAULT GETDATE(),
    TONGTIEN DECIMAL(18,2),
    TRANGTHAI NVARCHAR(50),
    DIACHINHAN NVARCHAR(255),
    FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH)
);
GO
CREATE TABLE CHITIETDONHANG(
    MADH INT,
    MASP INT,
    SOLUONG INT NOT NULL,
    DONGIA DECIMAL(18,2) NOT NULL,
    PRIMARY KEY(MADH,MASP),
    FOREIGN KEY(MADH) REFERENCES DONHANG(MADH),
    FOREIGN KEY(MASP) REFERENCES SANPHAM(MASP)
);
CREATE TABLE TONKHO(
    MATONKHO INT IDENTITY(1,1) PRIMARY KEY,
    MASP INT,
    SOLUONGNHAP INT ,
    SOLUONGXUAT INT DEFAULT 0,
    NGAYCAPNHAT DATETIME DEFAULT GETDATE(),
    FOREIGN KEY(MASP) REFERENCES SANPHAM(MASP)
);

