// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using duan_totnghiep.Models;

#nullable disable

namespace duan_totnghiep.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260703125230_ThemGhiChuDonHang")]
    partial class ThemGhiChuDonHang
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("duan_totnghiep.Models.Chitietdonhang", b =>
                {
                    b.Property<int>("Madh")
                        .HasColumnType("int")
                        .HasColumnName("MADH");

                    b.Property<int>("Masp")
                        .HasColumnType("int")
                        .HasColumnName("MASP");

                    b.Property<decimal>("Dongia")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("DONGIA");

                    b.Property<int>("Soluong")
                        .HasColumnType("int")
                        .HasColumnName("SOLUONG");

                    b.HasKey("Madh", "Masp")
                        .HasName("PK__CHITIETD__563D28E482B9A612");

                    b.HasIndex("Masp");

                    b.ToTable("CHITIETDONHANG", (string)null);
                });

            modelBuilder.Entity("duan_totnghiep.Models.Danhmuc", b =>
                {
                    b.Property<int>("Madm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MADM");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Madm"));

                    b.Property<string>("Mota")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("MOTA");

                    b.Property<string>("Tendm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TENDM");

                    b.HasKey("Madm")
                        .HasName("PK__DANHMUC__603F005C68B08698");

                    b.ToTable("DANHMUC", (string)null);
                });

            modelBuilder.Entity("duan_totnghiep.Models.Donhang", b =>
                {
                    b.Property<int>("Madh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MADH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Madh"));

                    b.Property<string>("Diachinhan")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("DIACHINHAN");

                    b.Property<string>("Ghichu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Makh")
                        .HasColumnType("int")
                        .HasColumnName("MAKH");

                    b.Property<int?>("Manv")
                        .HasColumnType("int")
                        .HasColumnName("MANV");

                    b.Property<DateTime?>("Ngaydat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("NGAYDAT")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Phuongthucthanhtoan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PHUONGTHUCTHANHTOAN");

                    b.Property<decimal>("Tongtien")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("TONGTIEN");

                    b.Property<string>("Trangthai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Madh")
                        .HasName("PK__DONHANG__603F00472BA9D9C5");

                    b.HasIndex("Makh");

                    b.HasIndex("Manv");

                    b.ToTable("DONHANG", (string)null);
                });

            modelBuilder.Entity("duan_totnghiep.Models.Giohang", b =>
                {
                    b.Property<int>("Magh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MAGH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Magh"));

                    b.Property<int>("Makh")
                        .HasColumnType("int")
                        .HasColumnName("MAKH");

                    b.Property<int>("Masp")
                        .HasColumnType("int")
                        .HasColumnName("MASP");

                    b.Property<DateTime?>("Ngaytao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("NGAYTAO")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("Soluong")
                        .HasColumnType("int")
                        .HasColumnName("SOLUONG");

                    b.HasKey("Magh")
                        .HasName("PK__GIOHANG__603F38A3B480C08A");

                    b.HasIndex("Makh");

                    b.HasIndex("Masp");

                    b.ToTable("GIOHANG", (string)null);
                });

            modelBuilder.Entity("duan_totnghiep.Models.Khachhang", b =>
                {
                    b.Property<int>("Makh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MAKH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Makh"));

                    b.Property<string>("Diachi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("DIACHI");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Hoten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("HOTEN");

                    b.Property<int?>("Matk")
                        .HasColumnType("int")
                        .HasColumnName("MATK");

                    b.Property<string>("Sdt")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("SDT");

                    b.HasKey("Makh")
                        .HasName("PK__KHACHHAN__603F592CEC605BBA");

                    b.HasIndex("Matk");

                    b.ToTable("KHACHHANG", (string)null);
                });

            modelBuilder.Entity("duan_totnghiep.Models.Khuyenmai", b =>
                {
                    b.Property<int>("Makm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MAKM");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Makm"));

                    b.Property<DateOnly?>("Ngaybatdau")
                        .HasColumnType("date")
                        .HasColumnName("NGAYBATDAU");

                    b.Property<DateOnly?>("Ngayketthuc")
                        .HasColumnType("date")
                        .HasColumnName("NGAYKETTHUC");

                    b.Property<int>("Phantramgiam")
                        .HasColumnType("int")
                        .HasColumnName("PHANTRAMGIAM");

                    b.Property<string>("Tenkm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TENKM");

                    b.Property<string>("Trangthai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Makm")
                        .HasName("PK__KHUYENMA__603F592BE78437AB");

                    b.ToTable("KHUYENMAI", (string)null);
                });

            modelBuilder.Entity("duan_totnghiep.Models.Nhanvien", b =>
                {
                    b.Property<int>("Manv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MANV");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Manv"));

                    b.Property<string>("Chucvu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CHUCVU");

                    b.Property<string>("Diachi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("DIACHI");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Hoten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("HOTEN");

                    b.Property<int?>("Matk")
                        .HasColumnType("int")
                        .HasColumnName("MATK");

                    b.Property<string>("Sdt")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("SDT");

                    b.HasKey("Manv")
                        .HasName("PK__NHANVIEN__603F511415B19D8E");

                    b.HasIndex("Matk");

                    b.ToTable("NHANVIEN", (string)null);
                });

            modelBuilder.Entity("duan_totnghiep.Models.Sanpham", b =>
                {
                    b.Property<int>("Masp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MASP");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Masp"));

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("GIA");

                    b.Property<string>("Hinhanh")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("HINHANH");

                    b.Property<int?>("Madm")
                        .HasColumnType("int")
                        .HasColumnName("MADM");

                    b.Property<int?>("Makm")
                        .HasColumnType("int")
                        .HasColumnName("MAKM");

                    b.Property<int?>("Math")
                        .HasColumnType("int")
                        .HasColumnName("MATH");

                    b.Property<string>("Mota")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("MOTA");

                    b.Property<DateTime?>("Ngaytao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Soluongton")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("SOLUONGTON");

                    b.Property<string>("Tensp")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TENSP");

                    b.HasKey("Masp")
                        .HasName("PK__SANPHAM__60228A3236F869AC");

                    b.HasIndex("Madm");

                    b.HasIndex("Makm");

                    b.HasIndex("Math");

                    b.ToTable("SANPHAM", (string)null);
                });

            modelBuilder.Entity("duan_totnghiep.Models.Taikhoan", b =>
                {
                    b.Property<int>("Matk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MATK");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Matk"));

                    b.Property<string>("Matkhau")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("MATKHAU");

                    b.Property<string>("Tendangnhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENDANGNHAP");

                    b.Property<string>("Trangthai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("TRANGTHAI");

                    b.Property<string>("Vaitro")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("VAITRO");

                    b.HasKey("Matk")
                        .HasName("PK__TAIKHOAN__602372168E262B7D");

                    b.HasIndex(new[] { "Tendangnhap" }, "UQ__TAIKHOAN__6C836FE5B3A643FF")
                        .IsUnique();

                    b.ToTable("TAIKHOAN", (string)null);
                });

            modelBuilder.Entity("duan_totnghiep.Models.Thuonghieu", b =>
                {
                    b.Property<int>("Math")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MATH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Math"));

                    b.Property<string>("Mota")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("MOTA");

                    b.Property<string>("Tenth")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TENTH");

                    b.HasKey("Math")
                        .HasName("PK__THUONGHI__6023721B1BF9AE32");

                    b.ToTable("THUONGHIEU", (string)null);
                });

            modelBuilder.Entity("duan_totnghiep.Models.Tonkho", b =>
                {
                    b.Property<int>("Matonkho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MATONKHO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Matonkho"));

                    b.Property<int>("Masp")
                        .HasColumnType("int")
                        .HasColumnName("MASP");

                    b.Property<DateTime?>("Ngaycapnhat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("NGAYCAPNHAT")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("Soluongnhap")
                        .HasColumnType("int")
                        .HasColumnName("SOLUONGNHAP");

                    b.Property<int?>("Soluongxuat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("SOLUONGXUAT");

                    b.HasKey("Matonkho")
                        .HasName("PK__TONKHO__9E1E7421F850ACF7");

                    b.HasIndex("Masp");

                    b.ToTable("TONKHO", (string)null);
                });

            modelBuilder.Entity("duan_totnghiep.Models.Chitietdonhang", b =>
                {
                    b.HasOne("duan_totnghiep.Models.Donhang", "Donhang")
                        .WithMany("Chitietdonhangs")
                        .HasForeignKey("Madh")
                        .IsRequired()
                        .HasConstraintName("FK__CHITIETDON__MADH__6383C8BA");

                    b.HasOne("duan_totnghiep.Models.Sanpham", "Sanpham")
                        .WithMany("Chitietdonhangs")
                        .HasForeignKey("Masp")
                        .IsRequired()
                        .HasConstraintName("FK__CHITIETDON__MASP__6477ECF3");

                    b.Navigation("Donhang");

                    b.Navigation("Sanpham");
                });

            modelBuilder.Entity("duan_totnghiep.Models.Donhang", b =>
                {
                    b.HasOne("duan_totnghiep.Models.Khachhang", "Khachhang")
                        .WithMany("Donhangs")
                        .HasForeignKey("Makh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__DONHANG__MAKH__60A75C0F");

                    b.HasOne("duan_totnghiep.Models.Nhanvien", "Nhanvien")
                        .WithMany("Donhangs")
                        .HasForeignKey("Manv")
                        .HasConstraintName("FK_DONHANG_NHANVIEN");

                    b.Navigation("Khachhang");

                    b.Navigation("Nhanvien");
                });

            modelBuilder.Entity("duan_totnghiep.Models.Giohang", b =>
                {
                    b.HasOne("duan_totnghiep.Models.Khachhang", "Khachhang")
                        .WithMany("Giohangs")
                        .HasForeignKey("Makh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__GIOHANG__MAKH__59063A47");

                    b.HasOne("duan_totnghiep.Models.Sanpham", "Sanpham")
                        .WithMany("Giohangs")
                        .HasForeignKey("Masp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GIOHANG_SANPHAM");

                    b.Navigation("Khachhang");

                    b.Navigation("Sanpham");
                });

            modelBuilder.Entity("duan_totnghiep.Models.Khachhang", b =>
                {
                    b.HasOne("duan_totnghiep.Models.Taikhoan", "Taikhoan")
                        .WithMany("Khachhangs")
                        .HasForeignKey("Matk")
                        .HasConstraintName("FK__KHACHHANG__MATK__4CA06362");

                    b.Navigation("Taikhoan");
                });

            modelBuilder.Entity("duan_totnghiep.Models.Nhanvien", b =>
                {
                    b.HasOne("duan_totnghiep.Models.Taikhoan", "Taikhoan")
                        .WithMany("Nhanviens")
                        .HasForeignKey("Matk")
                        .HasConstraintName("FK__NHANVIEN__MATK__4F7CD00D");

                    b.Navigation("Taikhoan");
                });

            modelBuilder.Entity("duan_totnghiep.Models.Sanpham", b =>
                {
                    b.HasOne("duan_totnghiep.Models.Danhmuc", "Danhmuc")
                        .WithMany("Sanphams")
                        .HasForeignKey("Madm")
                        .HasConstraintName("FK_SANPHAM_DANHMUC");

                    b.HasOne("duan_totnghiep.Models.Khuyenmai", "Khuyenmai")
                        .WithMany("Sanphams")
                        .HasForeignKey("Makm")
                        .HasConstraintName("FK_SANPHAM_KHUYENMAI");

                    b.HasOne("duan_totnghiep.Models.Thuonghieu", "Thuonghieu")
                        .WithMany("Sanphams")
                        .HasForeignKey("Math")
                        .HasConstraintName("FK__SANPHAM__MATH__5535A963");

                    b.Navigation("Danhmuc");

                    b.Navigation("Khuyenmai");

                    b.Navigation("Thuonghieu");
                });

            modelBuilder.Entity("duan_totnghiep.Models.Tonkho", b =>
                {
                    b.HasOne("duan_totnghiep.Models.Sanpham", "Sanpham")
                        .WithMany("Tonkhos")
                        .HasForeignKey("Masp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__TONKHO__MASP__693CA210");

                    b.Navigation("Sanpham");
                });

            modelBuilder.Entity("duan_totnghiep.Models.Danhmuc", b =>
                {
                    b.Navigation("Sanphams");
                });

            modelBuilder.Entity("duan_totnghiep.Models.Donhang", b =>
                {
                    b.Navigation("Chitietdonhangs");
                });

            modelBuilder.Entity("duan_totnghiep.Models.Khachhang", b =>
                {
                    b.Navigation("Donhangs");

                    b.Navigation("Giohangs");
                });

            modelBuilder.Entity("duan_totnghiep.Models.Khuyenmai", b =>
                {
                    b.Navigation("Sanphams");
                });

            modelBuilder.Entity("duan_totnghiep.Models.Nhanvien", b =>
                {
                    b.Navigation("Donhangs");
                });

            modelBuilder.Entity("duan_totnghiep.Models.Sanpham", b =>
                {
                    b.Navigation("Chitietdonhangs");

                    b.Navigation("Giohangs");

                    b.Navigation("Tonkhos");
                });

            modelBuilder.Entity("duan_totnghiep.Models.Taikhoan", b =>
                {
                    b.Navigation("Khachhangs");

                    b.Navigation("Nhanviens");
                });

            modelBuilder.Entity("duan_totnghiep.Models.Thuonghieu", b =>
                {
                    b.Navigation("Sanphams");
                });
#pragma warning restore 612, 618
        }
    }
}
